// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEB7OWyWX_5Iic_ZHMaKQkgoTcr62vd5Y',
    appId: '1:599037234481:web:0da8bcfe9dbddfc3f1f410',
    messagingSenderId: '599037234481',
    projectId: 'uas-ambw-c14190099',
    authDomain: 'uas-ambw-c14190099.firebaseapp.com',
    storageBucket: 'uas-ambw-c14190099.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMmKkPeGYI2fnH9wYX_WhYlUVjv_Butbc',
    appId: '1:599037234481:android:b1de4e297443295ef1f410',
    messagingSenderId: '599037234481',
    projectId: 'uas-ambw-c14190099',
    storageBucket: 'uas-ambw-c14190099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xusa1EQi06Dp0Vhbz83qwh-5y7j3mns',
    appId: '1:599037234481:ios:fb955298e3b0667af1f410',
    messagingSenderId: '599037234481',
    projectId: 'uas-ambw-c14190099',
    storageBucket: 'uas-ambw-c14190099.appspot.com',
    iosClientId: '599037234481-4jn5f0e6ju3cfkllh10lvl8it16qom10.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419009901',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xusa1EQi06Dp0Vhbz83qwh-5y7j3mns',
    appId: '1:599037234481:ios:fb955298e3b0667af1f410',
    messagingSenderId: '599037234481',
    projectId: 'uas-ambw-c14190099',
    storageBucket: 'uas-ambw-c14190099.appspot.com',
    iosClientId: '599037234481-4jn5f0e6ju3cfkllh10lvl8it16qom10.apps.googleusercontent.com',
    iosBundleId: 'com.example.c1419009901',
  );
}
